### ISSUE TITLE
Desktop Support?

### ISSUE THREAD

**Issue by The-Funk** [X-SLAYER/EzValidator#1]
EzValidator is fantastic! I was wondering if there are plans to expand support to desktop platforms and what such an endeavor might entail?

**Comment by X-SLAYER** [comment]
Hello yes i will try to update it to support all platform cuz it's dart code in the end he has no affect on other platforms

**Comment by The-Funk** [comment]
That's fantastic news! I will add EZValidator to my list of things to watch! I can close this issue if you'd like. I was just interested to know if you would be supporting it for a project I have in the works. 

Thank you! Appreciate your work!

**Comment by X-SLAYER** [comment]
i will tag you here once i upgrade it to close the issue no worries

**Comment by X-SLAYER** [comment]
Hello, you can try the plugin before I make a new release I already updated it to support all platforms :

```yaml
ez_validator:
  git:
    url: https://github.com/X-SLAYER/EzValidator.git
```

**Comment by The-Funk** [comment]
> Hello, you can try the plugin before I make a new release I already updated it to support all platforms :
> 
> ```yaml
> ez_validator:
>   git:
>     url: https://github.com/X-SLAYER/EzValidator.git
> ```

Sorry I never got back to you on this. For some reason GitHub stopped giving me notifications since halfway through August. I thought everyone was just ignoring me. 🤣

I saw the package has been updated! Can't wait to test it out!
