### ISSUE TITLE
How to validate dart objects?

### ISSUE THREAD

**Issue by johnnypark777** [X-SLAYER/EzValidator#14]
Hello, 
I have been looking at the examples and all of the validation seems to be on an JSON or a string, is there a way to validate dart object without having to json encode the dart object?

**Comment by X-SLAYER** [comment]
check this example below 

[nested-validation-example-with-ezvalidator](https://github.com/X-SLAYER/EzValidator?tab=readme-ov-file#nested-validation-example-with-ezvalidator)

**Comment by johnnypark777** [comment]
the `userProfileSchema` valides the following data: 
```dart
    {
      'firstName': 'John',
      'lastName': 'Doe',
      'email': 'john.doe@example.com',
      'age': 30,
      'contactDetails': {
        'mobile': '+12345678901',
      },
      'address': {
        'street': '123 Main St',
        'city': 'Anytown',
        'state': 'Anystate',
        'zipCode': 12345,
        'country': { }, // I will not define the country
      },
      'employment': {
        'current': 'Current Company',
        'previous': {
          'companyName': 'Previous Company',
          'position': 'Previous Position',
          'years': 5,
        },
      },
    }
```

The type of this data is a `Map<string, object>`.  I guess I should have specified the question on the case in which the Object is not mapped by strings.

For example, let's say I make a class called `Name`, and have two String parameters, firstName and lastName as follows:

```dart
class Name {
  final String firstName;
  final String lastName;
  Name({required this.x, required this.y});
}
```
And let's say I want to validate that firstName and lastName should at most be 30 characters, what should I do?
```dart
final myName = Name('John', 'Doe');
//validate myName.firstName and myName.lastName
```

**Comment by X-SLAYER** [comment]
you can add toMap to the class and validate it

**Comment by johnnypark777** [comment]
Ok, I guess I'll have to manually map it, was wondering if there was a way to avoid that. Thanks!
