### ISSUE TITLE
Validators should work with empty values by default

### ISSUE THREAD

**Issue by samishal1998** [X-SLAYER/EzValidator#2]
When I pass a validator to a TextField and the validator is not required, it still returns an error when the value is null or empty.

I had to wrap the validators using this function

```dart
String? Function(String?) ifNotEmptyValidator(Function validator){
  return (String? value){
    if(value?.isEmpty ?? true){
      return null;
    }else{
      return validator(value);
    }
  };
}

...

ifNotEmptyValidator(EzValidator().phone("Incorrect Format").build())
ifNotEmptyValidator(EzValidator().url("Incorrect Format").build())
```

Then I checked Your Implementation and I found that ***Optional defaults to false***, this is the main issue. Since you only have `required` function in the builder and not `notRequired`, then the default value for optional should be `true`, and should be changed to `false` when `required` is called, or you don't even need `optional`, if you always assume it's true unless `required` validation is added and call it first before all other validations.

```dart
class EzValidator {

  EzValidator();
  bool optional = true;
...
...

EzValidator required([String? message]) {
    optional = false;
    return _add((v) => v == null || v.trim().isEmpty
          ? message ?? globalLocale.required()
          : null);
  };
...
}
```
### Or
without optional, the existence of `requiredValidation` is an indicator of whether it's optional or not.
```dart
class EzValidator {

  final List<StringValidationCallback> validations = [];
  StringValidationCallback? requiredValidation;

...
...
...

  String? _test(String? value) {
    
     if ( (requiredValidation ==null) && (value == null || value.isEmpty)) {
        return null;
      }
    for (var validate in [requiredValidation, ...validations]) {
 
      final result = validate(value);
      if (result != null) {
        return result;
      }
    }
    return null;
  }

...
...

EzValidator required([String? message]) {
    requiredValidation = ((v) => v == null || v.trim().isEmpty
          ? message ?? globalLocale.required()
          : null);
    return this;
  };
...
}
```
### Or

Allow all validators to process nullable values and change `_add` to insert required validation at index 0, so the required validator will be called first.

**Comment by X-SLAYER** [comment]
If you want the field can be optional, you can pass the optional option like this 
```dart
EzValidator(optional: true).required().build()
```
it's missing in the documentation I will add it

**Comment by samishal1998** [comment]
I know it's available, I checked it in the implementation. what I'm saying is that it should be true by default. it doesn't make sense to be both optional and required, so `optional` should be `true` unless `required` is called.

the following makes more sense:
```dart
class EzValidator {

  EzValidator();
  bool optional = true; // Intialize it as true
...
...

EzValidator required([String? message]) {
    optional = false; // HERE You should make optional false
    return _add((v) => v == null || v.trim().isEmpty
          ? message ?? globalLocale.required()
          : null);
  };
...
}
```

also i think it would be better if `optional` is `private`

**Comment by X-SLAYER** [comment]
When you set the field optional to true, the required will be ignored automatically
check here [optional validation](https://github.com/X-SLAYER/EzValidator/blob/5aab3d029fe95a6ce5c222b742b246e68c3c2696/lib/validator/ez_validator_builder.dart#L29)
if set the optional is only inside the required not to like what it's right now, the other validation will work even if the field is optional 

For example, if the field is optional, but it has email validation, the email validation will be checked on a null, and it will return an error that the field is not a valid email address when.

**Comment by samishal1998** [comment]
I'm only saying it makes more sense for the default value of `optional` to be `true` since you only have `required` and ***not*** `notRequired` in the validations.

### Current Implementation
```dart
EzValidator().email().build() // 1 // this would not work with null and empty
EzValidator().email().required().build() // 2 // this would not work with null and empty

EzValidator(optional: true).email().required().build() // 3 // this would work with null and empty
```

- When you look at the two first code lines above, you assume that the first line works with optional values since the second line has `required()` but it doesn't. both lines basically behave the same way.

- And on line 3, you won't be able to determine the functionality just by looking at it, you have to either look at the implementation or run the code; because it's not clear from the line itself whether `optional` cancels `required` or the other way around.


### The Way I'm suggesting would result in the following
```dart
EzValidator().email().build() // the value would be optional 
EzValidator().email().required().build() // the value would be required
```

**Comment by X-SLAYER** [comment]
if you check the code you find that the validation process goes one by one so he will check the email() before reaching the required() method and make the optional = false, so the email() will check on a null value

and if we go with the process of making the optional = true by default and do 

```dart
EzValidator().email().required().build()
//  this will check on email validation before the required so if you pass an empty string it will show 
// 'Field not a valid email' instead user wanna see 'Field is required'
```

**Comment by X-SLAYER** [comment]
maybe in next version i'll make it looks more like yup with specifying each value type and validation
and I'll be happy if any pull request made in that sense to refactor it

**Comment by samishal1998** [comment]
> if you check the code you find that the validation process goes one by one so he will check the email() before reaching the required() method and make the optional = false, so the email() will check on a null value
> 
> and if we go with the process of making the optional = true by default and do
> 
> ```dart
> EzValidator().email().required().build()
> //  this will check on email validation before the required so if you pass an empty string it will show 
> // 'Field not a valid email' instead user wanna see 'Field is required'
> ```

No, Optional would be set to false before `_test` is  called. also, that's why I suggested in the first comment to always make the required validation the first.
```dart
class EzValidator {

  EzValidator();
  bool optional = true; // Initialize it as true
...
...

EzValidator required([String? message]) {
/* *************Here*************** */
    optional = false; // HERE You should make optional false
/* ******************************** */
    return _add((v) => v == null || v.trim().isEmpty
          ? message ?? globalLocale.required()
          : null);
  };
...
}
```

**Comment by samishal1998** [comment]
> if you check the code you find that the validation process goes one by one so he will check the email() before reaching the required() method and make the optional = false, so the email() will check on a null value
> 
> and if we go with the process of making the optional = true by default and do
> 
> ```dart
> EzValidator().email().required().build()
> //  this will check on email validation before the required so if you pass an empty string it will show 
> // 'Field not a valid email' instead user wanna see 'Field is required'
> ```

and 
```dart
EzValidator().email().build()
//  this will check on email validation even if you pass an empty string it will 
// show 'Field not a valid email'  even though it's not required
```

**Comment by samishal1998** [comment]
> maybe in next version i'll make it looks more like yup with specifying each value type and validation and I'll be happy if any pull request made in that sense to refactor it

That's my point the default behavior should be like yup. I'll gladly make make a pull request as soon as I have enough free time. Thank you for implementing the library btw

**Comment by X-SLAYER** [comment]
> > if you check the code you find that the validation process goes one by one so he will check the email() before reaching the required() method and make the optional = false, so the email() will check on a null value
> > and if we go with the process of making the optional = true by default and do
> > ```dart
> > EzValidator().email().required().build()
> > //  this will check on email validation before the required so if you pass an empty string it will show 
> > // 'Field not a valid email' instead user wanna see 'Field is required'
> > ```
> 
> and
> 
> ```dart
> EzValidator().email().build()
> //  this will check on email validation even if you pass an empty string it will 
> // show 'Field not a valid email'  even though it's not required
> ```

this will check on the email directly, will not check on the required the error will be email not valid, but no field is required 

for the moment, I'll keep it like that until I refactor the whole plugin cuz, in some cases, the optional option helps better. You can see that example 

```dart
// this will make one of the fields required depends on the other

EzSchema forgotPassword(String email, String phone) => EzSchema.shape({
      "phone": EzValidator(optional: email.isNotEmpty).required().build(),
      "email":
          EzValidator(optional: phone.isNotEmpty).required().email().build(),
    });
    
```

**Comment by samishal1998** [comment]
> > > if you check the code you find that the validation process goes one by one so he will check the email() before reaching the required() method and make the optional = false, so the email() will check on a null value
> > > and if we go with the process of making the optional = true by default and do
> > > ```dart
> > > EzValidator().email().required().build()
> > > //  this will check on email validation before the required so if you pass an empty string it will show 
> > > // 'Field not a valid email' instead user wanna see 'Field is required'
> > > ```
> > 
> > 
> > and
> > ```dart
> > EzValidator().email().build()
> > //  this will check on email validation even if you pass an empty string it will 
> > // show 'Field not a valid email'  even though it's not required
> > ```
> 
> this will check on the email directly, will not check on the required the error will be email not valid, but no field is required
> 
> for the moment, I'll keep it like that until I refactor the whole plugin cuz, in some cases, the optional option helps better. You can see that example
> 
> ```dart
> // this will make one of the fields required depends on the other
> 
> EzSchema forgotPassword(String email, String phone) => EzSchema.shape({
>       "phone": EzValidator(optional: email.isNotEmpty).required().build(),
>       "email":
>           EzValidator(optional: phone.isNotEmpty).required().email().build(),
>     });
>     
> ```

yes , I can see the value in the code, and yup has `yup.ref` for that, but a better solution would be to let `required` control optional.

```dart
class EzValidator {

  EzValidator();
  bool optional = true; // Initialize it as true
...
...

EzValidator required({String? message,bool condition = true}) {
/* *************Here*************** */
    optional = !condition; 
/* ******************************** */
    return _add((v) => v == null || v.trim().isEmpty
          ? message ?? globalLocale.required()
          : null);
  };
...
}
```

**Then** This will make either field required if the other is empty, it's more readable this way

 ```dart
 EzSchema forgotPassword(String email, String phone) => EzSchema.shape({
       "phone": EzValidator().required(condition:email.isEmpty).build(),
       "email": EzValidator().required(condition:phone.isEmpty).email().build(),
     });
     
 ```
